"""Authentication utilities for backend routes."""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from secrets import compare_digest
from typing import Tuple

from dotenv import load_dotenv
from fastapi import Depends, HTTPException
from fastapi.security import HTTPBasic, HTTPBasicCredentials
from starlette.status import HTTP_401_UNAUTHORIZED

load_dotenv()

logger = logging.getLogger(__name__)
security = HTTPBasic()


def _get_dashboard_credentials() -> Tuple[str, str]:
    """
    Retrieve dashboard credentials with priority:
    1. config/dashboard_auth.json (Generated by main.py)
    2. Environment variables
    3. Hardcoded fallback (dev only)
    """
    # 1. Try Environment Variables (Highest Priority - for overrides/testing)
    env_user = os.getenv("OMNIMIND_DASHBOARD_USER") or os.getenv("DASHBOARD_USER")
    env_pass = os.getenv("OMNIMIND_DASHBOARD_PASS") or os.getenv("DASHBOARD_PASS")

    if env_user and env_pass:
        logger.debug("Using credentials from environment variables")
        return env_user, env_pass

    # 2. Try JSON file (Source of Truth for Local Sovereignty)
    auth_file = Path(os.environ.get("OMNIMIND_DASHBOARD_AUTH_FILE", "config/dashboard_auth.json"))
    if auth_file.exists():
        try:
            with auth_file.open("r", encoding="utf-8") as f:
                data = json.load(f)
                user = data.get("user", "")
                pass_word = data.get("pass", "")
                logger.debug(f"Loaded credentials from {auth_file}: user={user}")
                return user, pass_word
        except Exception as e:
            logger.warning(f"Failed to load credentials from {auth_file}: {e}")

    # 3. Fallback (Should be avoided in production)
    logger.warning("Using fallback credentials (admin/omnimind2025!) - NOT PRODUCTION READY")
    return "admin", "omnimind2025!"


def verify_credentials(credentials: HTTPBasicCredentials = Depends(security)) -> str:
    """
    Verify HTTP Basic Auth credentials.
    """
    current_user, current_pass = _get_dashboard_credentials()

    logger.debug(f"Verifying credentials: {credentials.username} vs {current_user}")

    is_user = compare_digest(credentials.username, current_user)
    is_pass = compare_digest(credentials.password, current_pass)

    if not (is_user and is_pass):
        logger.warning(f"Authentication failed for user: {credentials.username}")
        raise HTTPException(
            status_code=HTTP_401_UNAUTHORIZED,
            detail="Invalid dashboard credentials",
            headers={"WWW-Authenticate": "Basic"},
        )
    logger.info(f"✅ Authentication successful for user: {credentials.username}")
    return credentials.username
