#!/usr/bin/env python3
"""
Autopoietic Service Runner.

Collects real system metrics and continuously executes the autopoietic cycle,
persisting each cycle in `data/autopoietic/cycle_history.jsonl`.
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from typing import Optional

# Ensure project root
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
sys.path.insert(0, PROJECT_ROOT)

from src.autopoietic.manager import AutopoieticManager
from src.autopoietic.meta_architect import ComponentSpec
from src.autopoietic.metrics_adapter import collect_metrics


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Continuous Autopoietic Execution Service")
    parser.add_argument(
        "--interval",
        type=float,
        default=10.0,
        help="Interval (seconds) between cycles.",
    )
    parser.add_argument(
        "--cycles",
        type=int,
        default=0,
        help="Number of cycles to execute (0 = infinite).",
    )
    parser.add_argument(
        "--history-path",
        type=str,
        default="data/autopoietic/cycle_history.jsonl",
        help="Path to persist cycle logs.",
    )
    parser.add_argument(
        "--metrics-path",
        type=str,
        default="data/monitor/real_metrics.json",
        help="Path to real metrics JSON file generated by the consciousness collector.",
    )
    return parser.parse_args()


def ensure_seed_spec(manager: AutopoieticManager) -> None:
    if manager.specs:
        return

    manager.register_spec(
        ComponentSpec(
            name="kernel_process",
            type="process",
            config={"priority": "high", "generation": "0"},
        )
    )


def main() -> None:
    args = parse_args()
    manager = AutopoieticManager(history_path=args.history_path)
    ensure_seed_spec(manager)

    total_cycles = args.cycles if args.cycles > 0 else None
    executed = 0

    try:
        while total_cycles is None or executed < total_cycles:
            sample = collect_metrics(real_metrics_path=args.metrics_path)
            log = manager.run_cycle(sample.strategy_inputs())
            executed += 1

            print(
                f"[Cycle {log.cycle_id}] strategy={log.strategy.name} "
                f"error={sample.error_rate:.3f} cpu={sample.cpu_usage:.1f}% "
                f"latency={sample.latency_ms:.0f}ms "
                f"components={','.join(log.synthesized_components) or 'none'}"
            )

            time.sleep(args.interval)
    except KeyboardInterrupt:
        print("\nAutopoietic service interrupted by user.")


if __name__ == "__main__":
    main()
