#!/bin/bash
# 🛡️ OmniMind Permission Setup
# Gera configuração do sudoers para permitir execução autônoma segura.

set -e

USER_NAME=$(whoami)
CONFIG_FILE="/etc/sudoers.d/omnimind_autonomous"
TEMP_FILE="omnimind_sudoers.tmp"

echo "🛡️ Configurando Permissões Autônomas para OmniMind..."
echo "   Usuário: $USER_NAME"

# Define os comandos permitidos (deve bater com privileged_commands.yaml)
# NOPASSWD permite execução sem senha (evita travamento)
cat > $TEMP_FILE <<EOF
# OmniMind Autonomous Permissions
# Generated by scripts/setup_permissions.sh on $(date)

# Permitir monitoramento eBPF
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/bpftrace

# Permitir limpeza de processos do projeto
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/pkill

# Permitir gerenciamento Docker
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/docker

# Permitir leitura de logs do sistema
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/journalctl, /usr/bin/dmesg

# Permitir ferramentas de rede e segurança (Network Security)
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/nmap, /usr/bin/ss, /usr/bin/tcpdump, /usr/sbin/iptables

# Permitir gerenciamento de serviços e hardware
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/systemctl, /usr/sbin/smartctl
EOF

echo "✅ Arquivo de configuração gerado: $TEMP_FILE"
echo "---------------------------------------------------"
cat $TEMP_FILE
echo "---------------------------------------------------"
echo ""
echo "⚠️  AÇÃO NECESSÁRIA:"
echo "Para ativar a autonomia do agente, execute o comando abaixo (pedirá senha 1 vez):"
echo ""
echo "   sudo mv $TEMP_FILE $CONFIG_FILE && sudo chown root:root $CONFIG_FILE && sudo chmod 0440 $CONFIG_FILE"
echo ""
echo "Após isso, o OmniMind poderá executar tarefas de segurança sem travar."
